# Generated by Django 3.0.5 on 2020-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200417_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door'), ('Indoor and outdoor', 'Indoor and outdoor')], max_length=200, null=True),
        ),
    ]
